[profile.default]
dotenv = ".env"
src = "src"
out = "out"
libs = ["lib"]
[fuzz]
no_parallel = true
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
